SmallShopManagementSystem/SmallShopManagementSystem/Controllers/PurchasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SSMS.BLL.BLL;
using SSMS.DatabaseContext.DatabaseContext;
using SSMS.Models.Models;

namespace SmallShopManagementSystem.Controllers
{
    public class PurchasesController : Controller
    {
        SSMSDbContext _db = new SSMSDbContext();
        private PurchaseBll _purchaseBll = new PurchaseBll();

        public ActionResult Add()
        {


            var model = new Purchase();
            model.SupplierLookUp = GetSupplierSelectListItems();
            model.ProductLookUp = GetProductSelectListItems();
            return View(model);
          
          

        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Purchase purchase)
        {
            if (ModelState.IsValid && purchase.PurchaseDetailses != null && purchase.PurchaseDetailses.Count > 0)
            {
                var model = new Purchase();

                model.SupplierLookUp = GetSupplierSelectListItems();
                model.ProductLookUp = GetProductSelectListItems();

                _db.Purchases.Add(purchase);
                var isPurchaseAdded = _db.SaveChanges();
                if (isPurchaseAdded > 0)
                {
                    return View(purchase);
                }


            }
            
            return View();


            //    try
            //    {
            //        var added = _purchaseBll.Add(purchase);
            //        if (added)
            //        {
            //            ViewBag.SMsg = "Save Success.";
            //        }
            //        else
            //        {
            //            ViewBag.FMsg = "Failed";
            //        }

            //    }
            //    catch (Exception exception)
            //    {
            //        ViewBag.FMsg = exception.Message;
            //    }
            //return View();



        }




        //public ActionResult Add()
        //{
        //    var model = new Purchase();
        //    model.SupplierLookUp = GetSupplierSelectListItems();
        //    model.ProductLookUp = GetProductSelectListItems();
        //    return View(model);
        //}



        //[HttpPost]
        //public ActionResult Add(Purchase purchase)
        //{
        //    var model = new Purchase();

        //    model.SupplierLookUp = GetSupplierSelectListItems();
        //    model.ProductLookUp = GetProductSelectListItems();
        //    try
        //    {
        //        var added = _purchaseBll.Add(purchase);
        //        if (added)
        //        {
        //            ViewBag.SMsg = "Save Success.";
        //        }
        //        else
        //        {
        //            ViewBag.FMsg = "Failed";
        //        }

        //    }
        //    catch (Exception exception)
        //    {
        //        ViewBag.FMsg = exception.Message;
        //    }
        //    return View(model);
        //}

        //[HttpGet]
        //public ActionResult Update()
        //{
        //    return View();
        //}
        //[HttpPost]
        //public ActionResult Update(Purchase purchase)
        //{
        //    var model = new Purchase();
        //    try
        //    {
        //        var aPurchase = _purchaseBll.GetPurchaseById(purchase.Id);
        //        if (aPurchase != null)
        //        {

        //            aPurchase.Date = purchase.Date;
        //            aPurchase.Bill = purchase.Bill;
        //            aPurchase.Supplier = purchase.Supplier;
        //            aPurchase.Product = purchase.Product;
        //            aPurchase.ManufacturedDate = purchase.ManufacturedDate;
        //            aPurchase.ExpireDate = purchase.ExpireDate;
        //            aPurchase.Quantity = purchase.Quantity;
        //            aPurchase.UnitPrice = purchase.UnitPrice;
        //            aPurchase.NewCostPrice = purchase.NewCostPrice;
        //            aPurchase.NewMrp = purchase.NewMrp;

        //            var isUpdate = _purchaseBll.Update(aPurchase);
        //            if (isUpdate)
        //            {
        //                ViewBag.SUpdate = "Update Success.";
        //            }
        //            else
        //            {
        //                ViewBag.FUpdate = "Update Failed.";
        //            }
        //        }
        //        else
        //        {
        //            ViewBag.FMsg = "Purchase not found.";
        //        }
        //    }
        //    catch (Exception exception)
        //    {
        //        ViewBag.FMsg = exception.Message;
        //    }
        //    return View(model);
        //}


        [HttpGet]
        public ActionResult Delete()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Delete(Purchase purchase)
        {
            try
            {
                var aPurchase = _purchaseBll.GetPurchaseById(purchase.Id);
                if (aPurchase != null)
                {
                    var isDelete = _purchaseBll.Delete(aPurchase);
                    if (isDelete)
                    {
                        ViewBag.SDeleted = "Delete Success.";
                    }
                    else
                    {
                        ViewBag.NSDelete = "Delete Failed.";
                    }
                }
                else
                {
                    ViewBag.FMsg = "Purchase not found.";
                }
            }
            catch (Exception exception)
            {

                ViewBag.FMsg = exception.Message;
            }
            return View();
        }

        //private const int index = 1;


        //public ActionResult Show(Purchase purchase)
        //{
        //    List<Purchase> aPurchase = _purchaseBll.Show(index);
        //    return View(aPurchase);

        //}
        public List<SelectListItem> GetSupplierSelectListItems()
        {
            var dataList = _db.Suppliers.ToList();

            var supplierSelectListItems = new List<SelectListItem>();

            supplierSelectListItems.AddRange(GetDefaultSelectListItem());

            if (dataList != null && dataList.Count > 0)
            {
                foreach (var supplier in dataList)
                {
                    var selectListItem = new SelectListItem();
                    selectListItem.Text = supplier.Name;
                    selectListItem.Value = supplier.Id.ToString();

                    supplierSelectListItems.Add(selectListItem);
                }
            }
            return supplierSelectListItems;
        }

        public List<SelectListItem> GetProductSelectListItems()
        {
            var dataList = _db.Products.ToList();

            var productSelectListItems = new List<SelectListItem>();

            productSelectListItems.AddRange(GetDefaultSelectListItem());

            if (dataList != null && dataList.Count > 0)
            {
                foreach (var product in dataList)
                {
                    var selectListItem = new SelectListItem();
                    selectListItem.Text = product.Name;
                    selectListItem.Value = product.Id.ToString();

                    productSelectListItems.Add(selectListItem);
                }
            }
            return productSelectListItems;
        }



        //public List<SelectListItem> GetDefaultSelectListItem()
        //{
        //    var dataList = new List<SelectListItem>();
        //    var defaultSelectListItem = new SelectListItem();
        //    defaultSelectListItem.Text = "---Select---";
        //    defaultSelectListItem.Value = "";
        //    dataList.Add(defaultSelectListItem);
        //    return dataList;
        //}


        public List<SelectListItem> GetDefaultSelectListItem()
        {
            var dataList = new List<SelectListItem>();
            var defaultSelectListItem = new SelectListItem();
            defaultSelectListItem.Text = "--------Select--------";
            defaultSelectListItem.Value = "";
            dataList.Add(defaultSelectListItem);
            return dataList;
        }



    }
}

SmallShopManagementSystem/SmallShopManagementSystem/Views/Purchases/Add.cshtml
@model SSMS.Models.Models.Purchase



    @using (Html.BeginForm("Add", "Purchases", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.AntiForgeryToken()
    <div class="form-horizontal">


        <div class="panel-group">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="panel-title">Purchase Header</div>
                </div>
                <div class="panel-body">
                    <div class="form-group row">
                        @Html.LabelFor(m => m.Date, "Date *", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBoxFor(m => m.Date, null, new { @class = "form-control" })
                        </div>

                    </div>
                    <div class="form-group row">
                        @Html.LabelFor(m => m.Bill, "Bill *", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBoxFor(m => m.Bill, null, new { @class = "form-control" })
                        </div>

                    </div>
                    
                    <div class="form-group row">
                        @Html.LabelFor(m => m.Supplier, "Supplier *", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @*@Html.DropDownListFor(m => m.SupplierId, Model.SupplierLookUp, new { @class = "form-control" })*@
                            @Html.DropDownListFor(m => m.SupplierId, Model.SupplierLookUp ?? new List<SelectListItem>(), new { @class = "form-control" })
                            
                        </div>

                    </div>
                </div>
            </div>
        </div>

        


        <div class="panel-group">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="panel-title">Added Purchase Details Items</div>
                </div>
                <div class="panel-body">
                </div>
                <div class="panel-body">
                    <div class="form-group row">
                        @Html.Label("IdProduct", "Product *", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.DropDownList("IdProduct", Model.ProductLookUp ?? new List<SelectListItem>(), new { @class = "form-control" })


                        </div>

                    </div>
                    <div class="form-group row">
                        @Html.LabelFor(m => m.Product.Code, "Code *", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBoxFor(m => m.Product.Code, null, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                        
                    </div>
                </div>
                <div class="panel-body">
                    <div class="form-group row">
                        @Html.Label("ProductManufacturedDate", "Manufactured Date *", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("ProductManufacturedDate", null, new { @class = "form-control" })
                        </div>

                    </div>
                    <div class="form-group row">
                        @Html.Label("ProductExpireDate", "ExpireDate *", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("ProductExpireDate", null, new { @class = "form-control" })
                        </div>

                    </div>
                </div>
                <div class="panel-body">
                    <div class="form-group row">
                        @Html.Label("ProductQuantity", "Quantity *", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("ProductQuantity", null, new { @class = "form-control" })
                        </div>

                    </div>
                    <div class="form-group row">
                        @Html.Label("ProductUnitPrice", "UnitPrice *", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("ProductUnitPrice", null, new { @class = "form-control" })
                        </div>

                    </div>
                </div>
                <div class="panel-body">
                    <div class="form-group row">
                        @Html.Label("ProductTotalPrice", "TotalPrice *", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("ProductTotalPrice", null, new { @class = "form-control" })
                        </div>

                    </div>
                    <div class="form-group row">
                        @Html.Label("ProductPreviousCostPrice", "PreviousCostPrice *", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("ProductPreviousCostPrice", null, new { @class = "form-control" })
                        </div>

                    </div>
                </div>
                <div class="panel-body">
                    <div class="form-group row">
                        @Html.Label("ProductPreviousMrp", "PreviousMrp *", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("ProductPreviousMrp", null, new { @class = "form-control" })
                        </div>

                    </div>
                    <div class="form-group row">
                        @Html.Label("ProductNewCostPrice", "NewCostPrice *", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("ProductNewCostPrice", null, new { @class = "form-control" })
                        </div>

                    </div>
                    <div class="form-group row">
                        @Html.Label("ProductNewMrp", "NewMrp *", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("ProductNewMrp", null, new { @class = "form-control" })
                        </div>
                        <div class="col-md-4 col-md-offset-4">
                            <input type="button" id="AddButton" class="btn btn-info" value="Add" />

                        </div>
                    </div>
                </div>
            </div>
        </div>



        <div class="panel-group">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="panel-title">Purchase Details</div>
                </div>
                <div class="panel-body">
                    <table class="table table-bordered table-hover table-striped table-responsive">
                        <thead>

                            <tr style="background-color: lightskyblue; color: white; font-weight: bold">
                                <td>SL</td>
                                <td>Products(Code)</td>
                                <td>Manufactured Date</td>
                                <td>Expire Date</td>
                                <td>Purchased Quantity</td>
                                <td>Unit Price</td>
                                <td>Total Price</td>
                                <td>Previous CP</td>
                                <td>Previous MRP</td>
                                <td>New CP</td>
                                <td>New MRP</td>
                                <td>Action</td>
                                
                            </tr>
                            
                                   
                            }
                          
                            

                        </thead>
                        <tbody id="PurchaseDetailsTable"></tbody>
                    </table>

                </div>


            </div>
            @*@Html.ActionLink("Delete", "Delete", "Purchases", new { @target = "_blank" })*@


        </div>
    </div>




    @*<input type="file" name="UploadFiles" class="btn btn-primary" multiple /><br />*@

    <hr />
    <div class="col-md-4 col-md-offset-4">
        <input type="submit" class="btn btn-info" value="Save" />
    </div>
}

@section scripts
{
  
<script src="~/Scripts/SSMS/Purchase/PurchaseCreate.js"></script>

}





           
@*@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    
</style>


<form method="POST">
    <h1>Purchase</h1>

    @if (ViewBag.SMsg != null)
    {
        <p>@ViewBag.SMsg</p>
    }
    @if (ViewBag.FMsg != null)
    {
        <p>@ViewBag.FMsg</p>
    }
    <table>
        <tr><td>@Html.LabelFor(c => c.Date)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.Date)</td></tr>
        <tr><td>@Html.LabelFor(c => c.Bill)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.Bill)</td></tr>
        <tr><td>@Html.LabelFor(c => c.Supplier)</td></tr>
        <tr><td>@Html.DropDownListFor(c => c.SupplierId, Model.SupplierLookUp, new { @class = "form-control" })</td></tr>
    </table>
    <br/>
    <table>
        
        
        <tr><td>@Html.LabelFor(c => c.Product)</td></tr>
        <tr><td>@Html.DropDownListFor(c => c.ProductId, Model.ProductLookUp, new { @class = "form-control" })</td></tr>
        <tr><td>@Html.LabelFor(c => c.Code)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.Code, new { @readonly = "readonly" })</td></tr>
        <tr><td>@Html.LabelFor(c => c.ManufacturedDate)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.ManufacturedDate)</td></tr>
        <tr><td>@Html.LabelFor(c => c.ExpireDate)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.ExpireDate)</td></tr>
        <tr><td>@Html.LabelFor(c => c.Quantity)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.Quantity)</td></tr>
        <tr><td>@Html.LabelFor(c => c.UnitPrice)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.UnitPrice)</td></tr>
        <tr><td>@Html.LabelFor(c => c.TotalPrice)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.TotalPrice, new { @readonly = "readonly" })</td></tr>
        <tr><td>@Html.LabelFor(c => c.PreviousCostPrice)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.PreviousCostPrice, new { @readonly = "readonly" })</td></tr>
        <tr><td>@Html.LabelFor(c => c.PreviousMrp)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.PreviousMrp, new { @readonly = "readonly" })</td></tr>
        <tr><td>@Html.LabelFor(c => c.NewCostPrice)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.NewCostPrice)</td></tr>
        <tr><td>@Html.LabelFor(c => c.NewMrp)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.NewMrp)</td></tr>
        
       
        
        <tr><td><input type="submit" value="Add" /></td></tr>

    </table>
    
  
<<<<<<< HEAD
</form>
=======
</form>*@




>>>>>>> d0175d36d0b5df2aabff86c124b87e2d60bdbf36

SmallShopManagementSystem/SmallShopManagementSystem/Views/Purchases/Delete.cshtml
@model SSMS.Models.Models.Purchase

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<form method="POST">
    <h1>Delete</h1>
    @if (ViewBag.SDeleted != null)
    {
        <p>Delete Successfully!!</p>
    }
    else if (ViewBag.NSDelete != null)
    {
        <p>Delete Failed!!</p>
    }
  
</form>

SmallShopManagementSystem/SmallShopManagementSystem/Views/Purchases/Show.cshtml
@model System.Collections.Generic.List<SSMS.Models.Models.Purchase>

<style>
    table {
        border-collapse: collapse;
    }

    table, td, th {
        border: 1px solid black;
    }
</style>
<h1> Purchase Details </h1>
@*<p id="HeadTitle"> Purchase Details </p>*@

@if (Model != null && Model.Count >= 0)
{
    var sl = 0;
    <table style="width: 80%">
        <tr id="tableHeader">

            <th>SL</th>
            <th>Products(Code)</th>
            <th>Manufactured Date</th>
            <th>Expire Date</th>
            <th>Purchased Quantity</th>
            <th>Unit Price</th>
            <th>Total Price</th>
            <th>Previous CP</th>
            <th>Previous MRP</th>
            <th>New CP</th>
            <th>New MRP</th>
            <th>Action</th>

        </tr>
        @foreach (var aPurchase in Model)
        {
            <tr>*@

                <td>@(++sl)</td>
                <td>@aPurchase.Product.Name
                    @aPurchase.Product.Code</td>
                <td>@aPurchase.ManufacturedDate</td>
                <td>@aPurchase.ExpireDate</td>
                <td>@aPurchase.Quantity</td>
                <td>@aPurchase.UnitPrice</td>
                <td>@aPurchase.TotalPrice</td>
                <td>@aPurchase.PreviousCostPrice</td>
                <td>@aPurchase.PreviousMrp</td>
                <td>@aPurchase.NewCostPrice</td>
                <td>@aPurchase.NewMrp</td>
                <td>
                    @Html.ActionLink("Update,", "Update", "Purchases", new { id = aPurchase.Id }, new { @target = "_blank" })
                    @Html.ActionLink("Delete", "Delete", "Purchases", new { id = aPurchase.Id }, new { @target = "_blank" })

                </td>

            </tr>
        }

    </table>
}

SmallShopManagementSystem/SmallShopManagementSystem/Views/Purchases/Update.cshtml
@model SSMS.Models.Models.Purchase
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<form method="POST">
    <h1>Purchase Update</h1>
    @if (ViewBag.SUpdate != null)
    {
        <p>@ViewBag.SUpdate</p>
    }
    else if (ViewBag.FUpdate != null)
    {
        <p>@ViewBag.FUpdate</p>
    }
    else if (ViewBag.FMsg != null)
    {
        <p>@ViewBag.FMsg</p>
    }
    <table>
        <tr><td>@Html.LabelFor(c => c.Date)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.Date)</td></tr>
        <tr><td>@Html.LabelFor(c => c.Bill)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.Bill)</td></tr>
        <tr><td>@Html.LabelFor(c => c.Supplier)</td></tr>
       
    </table>
    <br />
    <table>


        <tr><td>@Html.LabelFor(c => c.Product)</td></tr>
        @*<tr><td>@Html.DropDownListFor(c => c.ProductId, Model.ProductLookUp, new { @class = "form-control" })</td></tr>*@
        <tr><td>@Html.LabelFor(c => c.Code)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.Code, new { @readonly = "readonly" })</td></tr>
        <tr><td>@Html.LabelFor(c => c.ManufacturedDate)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.ManufacturedDate)</td></tr>
        <tr><td>@Html.LabelFor(c => c.ExpireDate)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.ExpireDate)</td></tr>
        <tr><td>@Html.LabelFor(c => c.Quantity)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.Quantity)</td></tr>
        <tr><td>@Html.LabelFor(c => c.UnitPrice)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.UnitPrice)</td></tr>
        <tr><td>@Html.LabelFor(c => c.TotalPrice)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.TotalPrice, new { @readonly = "readonly" })</td></tr>
        <tr><td>@Html.LabelFor(c => c.PreviousCostPrice)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.PreviousCostPrice, new { @readonly = "readonly" })</td></tr>
        <tr><td>@Html.LabelFor(c => c.PreviousMrp)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.PreviousMrp, new { @readonly = "readonly" })</td></tr>
        <tr><td>@Html.LabelFor(c => c.NewCostPrice)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.NewCostPrice)</td></tr>
        <tr><td>@Html.LabelFor(c => c.NewMrp)</td></tr>
        <tr><td>@Html.TextBoxFor(c => c.NewMrp)</td></tr>
        <tr><td><input type="submit" value="Update" /></td></tr>

    </table>

</form>